### Задача №1.1. Вариант 24.

#### Пункт 1

In [4]:
from scipy.optimize import linprog

In [6]:
c = [1, 1, -1, 0, 1]
A = [[-3, 1, 1, 0, 0], [4, 2, 0, -1, 0], [2, -1, 0, 0, 1]]
b = [3, 12,2]
res = linprog(c, A_eq=A, b_eq=b, method = 'simplex')
res

     con: array([8.8817842e-16, 0.0000000e+00, 0.0000000e+00])
     fun: -2.999999999999999
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([], dtype=float64)
  status: 0
 success: True
       x: array([2., 2., 7., 0., 0.])

Оптимизация выполнена успешно, ответ: x1 = 2, x2 = 2, x3 = 7, x4 = 0, x5 = 0.

#### Пункт 2

In [7]:
c = [2, 0, 0, 0, -1]
A = [[1, 8, 2, 0, 3], [3, 1, 0, 1, 1], [2, -1, 0, 1, 0]]
b = [51, 25, 10]
res = linprog(c, A_eq=A, b_eq=b, method = 'simplex')
res

     con: array([7.10542736e-15, 0.00000000e+00, 0.00000000e+00])
     fun: -15.0
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([], dtype=float64)
  status: 0
 success: True
       x: array([ 0.,  0.,  3., 10., 15.])

Ответ: x1 = 0, x2 = 0, x3 = 3, x4 = 10, x5 = 15.

#### Пункт 3

In [11]:
c = [-1, -1]
A = [[-4, 1], [2, -3], [2, 1]]
b = [1, 6, 8]
x0_bounds = (0, None)
x1_bounds = (0, None)
res = linprog(c, A_ub=A, b_ub=b, bounds = [x0_bounds, x1_bounds], method = 'simplex')
res

     con: array([], dtype=float64)
     fun: -6.833333333333334
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([-8.88178420e-16,  2.06666667e+01,  0.00000000e+00])
  status: 0
 success: True
       x: array([1.16666667, 5.66666667])

Ответ: x1 = 1.67, x2 = 5.67

#### Пункт 4

In [12]:
c = [-11, 24, 6]
A = [[11, -1, -2], [-1, -2, 3]]
b = [-3, -3]
x0_bounds = (0, None)
x1_bounds = (0, None)
x2_bounds = (0, None)
res = linprog(c, A_ub=A, b_ub=b, bounds = [x0_bounds, x1_bounds, x2_bounds], method = 'simplex')
res

     con: array([], dtype=float64)
     fun: 54.0
 message: 'Optimization terminated successfully.'
     nit: 2
   slack: array([0., 0.])
  status: 0
 success: True
       x: array([0.        , 2.14285714, 0.42857143])

Ответ: x1 = 0, x2 = 2.14, x3 = 0.43

### Задача 1.2

#### Вариант 70

In [14]:
c = [-1, -1, -1]
A = [[0.032, 0.031, 0.038], [0.02, 0.02, 0.008], [0.005, 0.005, 0.006], [10.2, 7.5, 5.8]]
b = [90, 30, 14, 16800]
x0_bounds = (350, None)
x1_bounds = (290, None)
x2_bounds = (1200, None)
res = linprog(c, A_ub=A, b_ub=b, bounds = [x0_bounds, x1_bounds, x2_bounds], method = 'simplex')
res

     con: array([], dtype=float64)
     fun: -2475.0
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([1.52962963, 0.        , 0.        , 0.        ])
  status: 0
 success: True
       x: array([ 370.37037037,  479.62962963, 1625.        ])

Ответ: трельяжей нужно выпустить 371, трюмо – 480, тумбочек – 1625.

#### Вариант 71

In [18]:
c = [-4.19, -3.02, -0.4]
A = [[0.032, 0.031, 0.038], [0.02, 0.02, 0.008], [0.005, 0.005, 0.006], [10.2, 7.5, 5.8]]
b = [90, 30, 14, 16800]
x0_bounds = (350, None)
x1_bounds = (290, None)
x2_bounds = (1200, None)
res = linprog(c, A_ub=A, b_ub=b, bounds = [x0_bounds, x1_bounds, x2_bounds], method = 'simplex')
res

     con: array([], dtype=float64)
     fun: -4414.5
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([ 12.05,   0.  ,   1.7 , 219.  ])
  status: 0
 success: True
       x: array([ 730.,  290., 1200.])

Ответ: трильяжей нужно 730, трюмо – 290 и тумбочек – 1200.

#### Вариант 72

In [20]:
c = [-119, -52]
A = [[22, 8]]
b = [14]
x0_bounds = (0, 440)
x1_bounds = (0, 720)
res = linprog(c, A_ub=A, b_ub=b, bounds = [x0_bounds, x1_bounds], method = 'simplex')
res

     con: array([], dtype=float64)
     fun: -91.0
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([0.])
  status: 0
 success: True
       x: array([0.  , 1.75])

Ответ: больших шайб - 0, маленьких - 1750.